### ISSUE TITLE
MAC v3_00 Error: Cannot find CTF archive

### ISSUE THREAD

**Issue by KohlerF** [SSDL-SNU/SNUPI#10] opened 2023-10-16 19:09 UTC
Hi,

I would love to try out the new v3_00 version on my Mac. However in my first test trying to run an example, I received an error: "Error: Cannot find CTF archive"  
version SNUPI_v2_01_mac works without problems. 

Test in the input file is:        
`H  EXAMPLE/Ex4_Triangle_dynamic`

terminal input:
```
sh ./run_SNUPI.sh /Applications/MATLAB/MATLAB_Runtime/R2022b
```
terminal output:
```
------------------------------------------
Setting up environment variables
---
DYLD_LIBRARY_PATH is .:/Applications/MATLAB/MATLAB_Runtime/R2022b/runtime/maci64:/Applications/MATLAB/MATLAB_Runtime/R2022b/bin/maci64:/Applications/MATLAB/MATLAB_Runtime/R2022b/sys/os/maci64
Error: Cannot find CTF archive '/Applications/SNUPI_v3_00_mac/SNUPI.app/Contents/Resources/SNUPI_mcr/.META/manifest.xml'. 
```

Browsing through the directories, the .META folder indeed does not exist. Please let me know if you require further information. Thanks for your help. 

Best,
Fabian

**Comment by SSDL-SNU** [comment] 2023-11-09 11:02
Hi Fabian,

Sorry for late reply because I didn't received any alert.

I will check and let you know. If you already solved this issue, please
inform me.

Thank you so much.

Sincerely,
Jae Young

**Comment by SSDL-SNU** [comment] 2023-11-10 18:51
Hi Fabian,

I examined the files for the Mac version, and it worked well. I think the
current issue was caused by the system or installation. Could you try to
remove all other versions of runtime and install only version R2022b? If it
does not work, please let me know.
Sorry for the usage, and thank you for the report.

Best,
Jae Young


2023년 11월 9일 (목) 오전 6:02, snupi ssdl ***@***.***>님이 작성:

**Comment by Dan-X** [comment] 2023-11-16 11:37
Dear Jae Young,
I have exactly the same problem on my mac as @KohlerF.
Removing the other Matlab runtime (v96) did not help.
```
(base) ➜  SNUPI_v3_00_mac sh ./run_SNUPI.sh /Applications/MATLAB/MATLAB_Runtime/R2022b
```
output:
```
'------------------------------------------
Setting up environment variables
---
DYLD_LIBRARY_PATH is .:/Applications/MATLAB/MATLAB_Runtime/R2022b/runtime/maci64:/Applications/MATLAB/MATLAB_Runtime/R2022b/bin/maci64:/Applications/MATLAB/MATLAB_Runtime/R2022b/sys/os/maci64
Error: Cannot find CTF archive '/Users/u0162211/Library/CloudStorage/OneDrive-KULeuven/matlab-code/SNUPI/SNUPI_v3_00_mac/SNUPI.app/Contents/Resources/SNUPI_mcr/.META/manifest.xml'.
```

System Version: macOS 14.1 (23B74)

Best,
Xin

**Comment by elija-feigl** [comment] 2023-11-16 13:01
Hi, I encounter the same problem.
I run MacOs 13.5 on aM2 chip

one additional notes:
the DYLD_LIBRARY_PATH suggested by the Runtime Installer is different from the one in run_snupi.sh. manually setting the variable did not resolve the error
- Matlab: /Applications/MATLAB/MATLAB_Runtime/R2022b/runtime/maci64:/Applications/MATLAB/MATLAB_Runtime/R2022b/bin/maci64:/Applications/MATLAB/MATLAB_Runtime/R2022b/sys/osmaci64:/Applications/MATLAB/MATLAB_Runtime/R2022b/extern/bin/maci64
- SNUPI: /Applications/MATLAB/MATLAB_Runtime/R2022b/runtime/maci64:/Applications/MATLAB/MATLAB_Runtime/R2022b/bin/maci64:/Applications/MATLAB/MATLAB_Runtime/R2022b/sys/os/maci64

Best, elija

**Comment by SSDL-SNU** [comment] 2023-11-16 21:05
Hi, I read the replies. Thank you all for testing and reporting. I will
re-test and let you know as soon as I can.

Additionally, I wonder if other files for Windows or Linux worked well. I
will check all files at once if they have the same issue on execution.

Thank you.
Jae Young

**Comment by SSDL-SNU** [comment] 2023-11-22 02:42
Hi, I uploaded a modified file for Mac. It was tested on MacBook Pro (Ventura 13.4) and Mac Pro (Ventura 13.0.1). Please check, and I hope there is no issue in execution.

Thank you.
Jae Young

**Comment by scikat** [comment] 2023-11-28 00:43
Hi, just wanted to give some feedback that the Mac version is now working for me. I was having the same issue as the others before you uploaded the modified file. Thank you for resolving this! :)

Best,
K

**Comment by elija-feigl** [comment] 2023-11-28 09:25
hi, same here. thank you for the great work! 
best, elija

**Comment by Dan-X** [comment] 2023-11-28 14:32
Yes, same here, the problem is solved! thank you very much!
best, 
Xin

**Comment by SSDL-SNU** [comment] 2023-11-28 15:39
Thank you all.
Jae Young

**Closed as completed by SSDL-SNU** 2023-11-28 15:39 UTC
