### ISSUE TITLE
Inconsistency between the design files and the oxDNA output.

### ISSUE THREAD

**Issue by zoombya** [SSDL-SNU/SNUPI#11] opened 2024-01-11 09:52 UTC
When I'm running the example triangle structure 4 asking for the oxDNA output the resulting structure is missing the single stranded regions specified in the example design file.
Have tried to run this on SNUPI3, setting the following input file option. 
`STT_FINL_OX     1`
Am not sure if other versions are affected. 
![image](https://github.com/SSDL-SNU/SNUPI/assets/1756978/044f42fc-a4de-4566-869a-a36e7b402f9b)

**Comment by SSDL-SNU** [comment] 2024-01-17 14:04
Oh, I'm going to check that, and let you know in several days. Thank you
for testing.

Best,
Jae Young

**Comment by m-matthies** [comment] 2024-01-19 14:21
Great thanks, highly appreciate any help !

Also another issue is that if I try to run the program on MacOS (M3)
`./SNUPI.app/Contents/MacOS/SNUPI` 
the first 3 examples work fine, producing output and it brakes on example 4
with the following output 
```
%--------------------------------------------------------------------------
%----------------------- POST-PROCESSING (DYNAMIC) ------------------------
%--------------------------------------------------------------------------
  - INPUT FILE: Ex4_Triangle_dynamic
%--------------------------------------------------------------------------
  - CONFIGURATION PLOT (DYNAMIC)
  - MODEL FILE GENERATION (DYNAMIC)
  - RMSD & RMSF CALCULATION (DYNAMIC)
  - WALL TIME (RMSD & RMSF) = 0.12 [s]
  - RMSD PLOT (DYNAMIC)
  - RMSF PLOT (DYNAMIC)
  - CORRELATION CALCULATION (DYNAMIC)
Index in position 3 exceeds array bounds.

Error in cal_DYN_CORR (line 42)

Error in MAIN (line 1255)

MATLAB:badsubscript

```

**Comment by SSDL-SNU** [comment] 2024-01-25 01:32
Hi, I fixed the issue in generating oxDNA input for single-stranded nucleotides. The updated version would work well (v3_01).
To generate single-stranded parts, the option for exporting pdb or oxdna should be changed to "PDB_EX_IND    2". 
The generated nucleotides will have equally distributed positions using the connected terminal base-pairs. You could use the oxView to modify them into physically correct positions. 
Also, I cannot reproduce the issue on my mac. Could you reinstall the runtime or test it on another computer? Sorry for that.

Thank you.
Jae Young

![image](https://github.com/SSDL-SNU/SNUPI/assets/61811152/54801e76-25d9-40f7-8c54-8a949d1f5fad)

**Comment by m-matthies** [comment] 2024-01-25 11:17
This looks great, thank you so much! 

Could you possibly give me an example on how you run the ./run script, 
I am able to start the examples just by running the executable directly (latest version).
And i don't encounter the problem with the latest executable. 

(as this more of a comment than an actual issue, i will close the issue)
Great thanks again for your help!

**Closed as completed by m-matthies** 2024-01-25 11:17 UTC

**Comment by SSDL-SNU** [comment] 2024-01-25 14:29
Hi, you can find the details of how to run in mac OS in READEME.txt.

------------------------------------------------------------------------------------------
* How to run the program (Mac)
------------------------------------------------------------------------------------------
- Open the terminal
- Move the current directory to the SNUPI folder
- Give permission to execute
	chmod +x *
- Execute SNUPI in the FILE folder using Terminal
	./run_SNUPI.sh <mcr_directory>
- For example,
	./run_SNUPI.sh /Applications/MATLAB/MATLAB_Runtime/R2022b
- The result files will be saved in the 'OUTPUT' folder.
- To analyze custom design files, modify 'Input.txt'

------------------------------------------------------------------------------------------

Thank you.
Jae Young

**Comment by m-matthies** [comment] 2024-01-25 14:41
ok, cool 
being in the snupi folder this also works 
```
/Users/usr/SNUPI_v3_01_mac
(base) ➜  SNUPI_v3_01_mac SNUPI.app/Contents/MacOS/SNUPI     
```
